server:
  port: 8080

spring:
  application:
    name: hello-service
  #profiles:
  #  active: dev

eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
     defaultZone: http://localhost:8761/eureka
     ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: true
info:
  app.name: HELLO-provide
  company.name: dding
  build.artifactId: $project.artifactId$
  build.version: 0.0.1