server:
  port: 8081

spring:
  application:
    name: hello-consumer
  #profiles:
  #  active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app.name: HELLO-consumer
  company.name: dding
  build.artifactId: $project.artifactId$
  build.version: 0.0.1