server:
  port: 8082

spring:
  application:
    name: user-service
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      ####当前服务的注册中心地址
     defaultZone: http://localhost:8761/eureka
     ###需要将服务注册到eureka上
    register-with-eureka: true
    #####需要去检索服务信息
    fetch-registry: true
info:
  app.name: user-service
  company.name: dding
  build.artifactId: $project.artifactId$
  build.version: 0.0.1