server:
  port: 8082

spring:
  application:
    name: consul-provider
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0


info:
  app.name: user-service
  company.name: dding
  build.artifactId: $project.artifactId$
  build.version: 0.0.1