server:
  port: 8761
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: registry-eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

